export const GET_USERS = "GET_USERS";
export const CREATE_USERS = "CREATE_USERS";
export const EMAIL_VERIFICATION = "EMAIL_VERIFICATION";
export const OTP_VERIFICATION = "OTP_VERIFICATION";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const LOGIN = "LOGIN";

// ashfi
export const GET_PLAYERS = "GET_PLAYERS";
export const GET_SINGLE_PLAYER = "GET_SINGLE_PLAYER";

export const GET_BATSMAN_STATS = "GET_BATSMAN_STATS";
export const GET_ODI_BATSMAN_STATS = "GET_ODI_BATSMAN_STATS";
export const GET_T20_BATSMAN_STATS = "GET_T20_BATSMAN_STATS";
export const GET_ODI_BOWLER_STATS = "GET_ODI_BOWLER_STATS";
export const GET_T20_BOWLER_STATS = "GET_T20_BOWLER_STATS";
export const GET_TEST_BOWLER_STATS = "GET_TEST_BOWLER_STATS";
export const GET_TOP_PLAYERS = "GET_TOP_PLAYERS";

// export const CREATE_PLAYER = "CREATE_PLAYER";
// export const EDIT_PLAYER = "EDIT_PLAYER";
// export const DELETE_PLAYER = "DELETE_PLAYER";
// export const GET_PLAYER_SEARCH = "GET_PLAYER_SEARCH";

// export const GET_TEAMS = "GET_TEAMS";
// export const GET_MATCHBYTEAMID = "GET_MATCHBYTEAMID";
// export const GET_RANKS = "GET_RANKS";

export const GET_NEWS = "GET_NEWS";
export const GET_SEARCH = "GET_SEARCH";

// yatin
export const GET_MATCHES_BY_DATE = "GET_MATCHES_BY_DATE";
export const GET_RECENT_MATCHES_DATE = "GET_RECENT_MATCHES_DATE";
export const GET_MATCH_DETAILS_BY_ID = "GET_MATCH_DETAILS_BY_ID";
export const GET_MATCH_SCORECARD_DETAILS_BY_ID =
  "GET_MATCH_SCORECARD_DETAILS_BY_ID";
export const GET_MANHATTAN_GRAPH_BY_ID = "GET_MANHATTAN_GRAPH_BY_ID";
export const GET_PIECHART_ONE_GRAPH_BY_ID = "GET_PIECHART_ONE_GRAPH_BY_ID";
export const GET_PIECHART_TWO_GRAPH_BY_ID = "GET_PIECHART_TWO_GRAPH_BY_ID";

//piyush
export const CREATE_TEAM = "CREATE_TEAM";
export const EDIT_TEAM = "EDIT_TEAM";
export const DELETE_TEAM = "DELETE_TEAM";
export const GET_TEAM_SEARCH = "GET_TEAM_SEARCH";
export const CREATE_PLAYER = "CREATE_PLAYER";
export const EDIT_PLAYER = "EDIT_PLAYER";
export const DELETE_PLAYER = "DELETE_PLAYER";
export const GET_PLAYER_SEARCH = "GET_PLAYER_SEARCH";
export const GET_ALLTEAMS = "GET_ALLTEAMS";
export const ERROR_TYPE = "ERROR_TYPE";
export const LOADING_START = "LOADING_START";
export const LOADING_STOP = "LOADING_STOP";

// aditya

export const GET_TEAMS = "GET_TEAMS";
export const GET_MATCHBYTEAMID = "GET_MATCHBYTEAMID";
export const GET_RANKS = "GET_RANKS";
export const GET_TEAM_BATSMEN = "GET_TEAM_BATSMEN";
export const GET_TEAM_BOWLERS = "GET_TEAM_BOWLERS";
export const GET_TEAM_FIXTURES = "GET_TEAM_FIXTURES";
export const GET_HIGHEST_TOTALS = "GET_HIGHEST_TOTALS";
export const GET_LOWEST_TOTALS = "GET_LOWEST_TOTALS";

// Nikhil
export const GET_NEWS_ID = "GET_NEWS_ID";
export const GET_HOME_RECENT_MATCHES = "GET_HOME_RECENT_MATCHES";
